language: objective-c
osx_image: xcode8

before_install:
  - carthage bootstrap --verbose

script:
  - open -a "simulator" --args -CurrentDeviceUDID A84965FC-070D-4EAF-83E8-84FFE99F5866
  - xcodebuild clean build test -project ApiConnector.xcodeproj -scheme ApiConnector  -destination 'platform=iOS Simulator,name=iPhone 6'

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: true
