language: objective-c
osx_image: xcode8

before_install:
  - carthage bootstrap --verbose

script:
  - xcodebuild clean build test -project ApiConnector.xcodeproj -scheme ApiConnector

notifications:
  email: true
